### ISSUE TITLE
Why is there no destructor in Deque.cpp?

### ISSUE THREAD

**Issue by DenyShew** [Anjewka/data-structures#1]

**Comment by Anjewka** [comment]
обновил

пн, 22 мар. 2021 г. в 21:15, DenyShew ***@***.***>:

**Comment by Anjewka** [comment]
Updated

**Comment by DenyShew** [comment]
Now make the destructor virtual and change push_back(T data) to push_back(T&& data)

**Comment by DenyShew** [comment]
And, I forgot, change the int type to unsigned or just size_t in methods that work with sizes, for example, the constructor
